name: Mirroring

on: [push, pull_request, issues, delete, issue_comment, pull_request_review, pull_request_review_comment, pull_request_target, create]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.0
        with:
          target_repo_url:
            git@git.swmgit.org:swm-13-main/13_swm29/eureka-backend.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
